#!/usr/bin/env groovy

/*
 * Template Jenkinsfile for process-engine projects.
 *
 * For this template to work you need some custom
 * scripts in your package.json. Below is a example
 * for those scripts:
 *  (...)
 *  "scripts": {
 *    "lint": "gulp lint",
 *    "build": "gulp build",
 *    "build-schemas": "gulp typescript-schema"
 *    "build-doc": "gulp doc",
 *    "test": "gulp test",
 *  },
 *  (...)
 *
 */
pipeline {
  agent any
  tools {
    nodejs "node-lts"
  }

  stages {
    stage('prepare') {
      steps {
        script {
          rawPackageVersion = sh returnStdout: true, script: 'node --print --eval "require(\'./package.json\').version"'
          PACKAGE_VERSION = rawPackageVersion.trim()
          echo "Package version is '" + PACKAGE_VERSION + "'"
        }
        sh 'node --version'
        sh 'npm install --ignore-scripts'
      }
    }
    stage('lint') {
      steps {
        sh 'node --version'
        /* we do not want the linting to cause a failed build */
        sh 'npm run lint || true'
      }
    }
    stage('build') {
      steps {
        sh 'node --version'
        sh 'npm run build'
        sh 'npm run build-schemas'
        sh 'npm run build-doc'
      }
    }
    stage('test') {
      steps {
        sh 'node --version'
        sh 'npm run test'
      }
    }
    stage('publish') {
      steps {
        script {
          def branch = env.BRANCH_NAME;

          if (branch == 'master' && env.GIT_PREVIOUS_COMMIT != env.GIT_COMMIT) {
            script {
              // let the build fail if the version does not match normal semver
              def isNormalVersion = PACKAGE_VERSION =~ /\d+\.\d+\.\d+/
              if (!isNormalVersion.matches()) {
                error('Only non RC Versions are allowed in master')
              }
            }
            nodejs(configId: 'developers5minds-token', nodeJSInstallationName: 'node-lts') {
              sh 'node --version'
              sh 'npm publish --ignore-scripts'
            }

          } else {
            // when not on master, publish a prerelease based on the package version, the
            // current git commit and the build number.
            // the published version gets tagged as the branch name.
            def shortGitCommit = env.GIT_COMMIT.substring(0, 8);
            def publishVersion = "${PACKAGE_VERSION}-${shortGitCommit}-b${env.BUILD_NUMBER}";
            def publishTag = branch.replace("/", "~");
            nodejs(configId: 'process-engine-ci-token', nodeJSInstallationName: 'node-lts') {
              sh 'node --version'
              sh "npm version ${publishVersion} --no-git-tag-version --force"
              sh "npm publish --tag ${publishTag} --ignore-scripts"
            }
          }
        }
      }
    }
  }
}
