'use strict';

const should = require('should');
const TestFixtureProvider = require('../dist/commonjs').TestFixtureProvider;

describe.skip('Conditional Boundary Event - ', () => {

  let testFixtureProvider;

  const processModelId = 'boundary_event_conditional';
  const startEventId = 'StartEvent_1';
  const useAutoGeneratedCorrelationId = undefined;

  before(async () => {
    testFixtureProvider = new TestFixtureProvider();
    await testFixtureProvider.initializeAndStart();

    await testFixtureProvider.importProcessFiles([processModelId]);
  });

  after(async () => {
    await testFixtureProvider.tearDown();
  });

  it('should return "lesser", if the initial token is lesser than or equal 4.', async () => {

    const result = await testFixtureProvider.executeProcess(processModelId, startEventId, useAutoGeneratedCorrelationId, 4);

    should(result).have.property('currentToken');
    should(result.currentToken.current).be.eql('lesser');
  });

  it('should return "greater", if the initial token is greater than or equal 6.', async () => {

    const result = await testFixtureProvider.executeProcess(processModelId, startEventId, useAutoGeneratedCorrelationId, 6);

    should(result).have.property('currentToken');
    should(result.currentToken.current).be.eql('greater');
  });
});
