FROM node:8-alpine

RUN apk add --no-cache git

WORKDIR /usr/src/app

COPY gulpfile.js ./
COPY index.js ./
COPY ioc_module.js ./
COPY package.json ./
COPY tsconfig.json ./
COPY bpmn ./bpmn
COPY config ./config
COPY src ./src
COPY test ./test

RUN npm install
RUN npm run build
