
name: Node CI

on:
  push:
    branches:
      - "*"
      - "*/*"

jobs:
  test_sqlite:
    name: "Test with SQLite"
    if: "!(contains(github.actor, 'process-engine-ci') || contains(github.actor, 'admin'))"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Install Dependencies
      working-directory: ./_integration_tests
      run: |
        npm i

    - name: Build
      working-directory: ./_integration_tests
      run: npm run build

    - name: Run Tests
      working-directory: ./_integration_tests
      run: npm run test-sqlite

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: 'Test with SQLite'
        mention_if: 'always'
        url: ${{ secrets.SLACK_WEBHOOK }}
        commit: true
        token: ${{ secrets.GH_TOKEN }}

  test_postgres:
    name: "Test with Postgres"
    if: "!(contains(github.actor, 'process-engine-ci') || contains(github.actor, 'admin'))"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Setup Postgres Container
      working-directory: ./_integration_tests
      run: node scripts/setup_postgres/postgres_docker.js start

    - name: Install Dependencies
      working-directory: ./_integration_tests
      run: |
        npm i

    - name: Build
      working-directory: ./_integration_tests
      run: npm run build

    - name: Run Tests
      working-directory: ./_integration_tests
      run: npm run test-postgres

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: 'Test with Postgres'
        mention_if: 'always'
        url: ${{ secrets.SLACK_WEBHOOK }}
        commit: true
        token: ${{ secrets.GH_TOKEN }}

  test_mysql:
    name: "Test with MySQL"
    if: "!(contains(github.actor, 'process-engine-ci') || contains(github.actor, 'admin'))"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Setup MySQL Container
      working-directory: ./_integration_tests
      run: node scripts/setup_mysql/mysql_docker.js start

    - name: Install Dependencies
      working-directory: ./_integration_tests
      run: |
        npm i

    - name: Build
      working-directory: ./_integration_tests
      run: npm run build

    - name: Run Tests
      working-directory: ./_integration_tests
      run: npm run test-mysql

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: 'Test with MySQL'
        mention_if: 'always'
        url: ${{ secrets.SLACK_WEBHOOK }}
        commit: true
        token: ${{ secrets.GH_TOKEN }}

  slack_notification:
    name: "Send Slack Notification"
    needs: [test_sqlite, test_postgres, test_mysql]
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Slack Notification
      uses: homoluctus/slatify@master
      with:
        type: ${{ job.status }}
        job_name: 'Tests for ProcessEngineCoreMeta'
        mention_if: 'always'
        url: ${{ secrets.SLACK_WEBHOOK }}
        commit: true
        token: ${{ secrets.GH_TOKEN }}

